import type { Organization } from "./OrgDetailSheet";

export const dummyOrganizations: Organization[] = [
  {
    id: "1",
    name: "Shri Krishna Seva Trust",
    contactPerson: "Rajesh Kumar",
    email: "rajesh@krishnaseva.org",
    phone: "+91 98765 43210",
    gstOrRegId: "29ABCDE1234F1ZK",
    address: "42, Temple Road, Basavanagudi",
    city: "Bengaluru",
    pincode: "560004",
    description: "A trust dedicated to community service through temple activities, food distribution, and educational support for underprivileged children across Karnataka.",
    logoUrl: "",
    status: "pending",
    socialLinks: {
      website: "https://krishnaseva.org",
      facebook: "https://facebook.com/krishnaseva",
      instagram: "https://instagram.com/krishnaseva",
    },
    submittedAt: "2 days ago",
  },
  {
    id: "2",
    name: "Hope Orphanage Foundation",
    contactPerson: "Meena Sharma",
    email: "meena@hopefoundation.in",
    phone: "+91 87654 32109",
    gstOrRegId: "HF-REG-2019-4521",
    address: "15, MG Road, Indiranagar",
    city: "Bengaluru",
    pincode: "560038",
    description: "Providing shelter, education, and holistic care to orphaned and abandoned children since 2005. Currently supporting over 120 children.",
    logoUrl: "",
    status: "pending",
    socialLinks: {
      website: "https://hopefoundation.in",
      twitter: "https://twitter.com/hopefdn",
      linkedin: "https://linkedin.com/company/hopefoundation",
    },
    submittedAt: "3 days ago",
  },
  {
    id: "3",
    name: "Green Earth Initiative",
    contactPerson: "Arjun Patel",
    email: "arjun@greenearth.co.in",
    phone: "+91 76543 21098",
    gstOrRegId: "GEI-NGO-2021-7789",
    address: "8, Koramangala 4th Block",
    city: "Bengaluru",
    pincode: "560034",
    description: "Environmental conservation NGO focused on urban tree planting, waste management education, and sustainable living workshops.",
    logoUrl: "",
    status: "approved",
    socialLinks: {
      website: "https://greenearth.co.in",
      instagram: "https://instagram.com/greenearthin",
      facebook: "https://facebook.com/greenearthin",
    },
    submittedAt: "1 week ago",
  },
  {
    id: "4",
    name: "Annapurna Food Bank",
    contactPerson: "Lakshmi Devi",
    email: "lakshmi@annapurnafoodbank.org",
    phone: "+91 65432 10987",
    gstOrRegId: "AFB-TRUST-2018-3344",
    address: "22, Jayanagar 9th Block",
    city: "Bengaluru",
    pincode: "560069",
    description: "Fighting hunger by collecting surplus food from restaurants and events, redistributing to homeless shelters and low-income communities.",
    logoUrl: "",
    status: "info_requested",
    socialLinks: {
      website: "https://annapurnafoodbank.org",
      facebook: "https://facebook.com/annapurnafb",
    },
    submittedAt: "5 days ago",
  },
  {
    id: "5",
    name: "Vidya Bharati Education Society",
    contactPerson: "Dr. Suresh Nair",
    email: "suresh@vidyabharati.edu.in",
    phone: "+91 54321 09876",
    gstOrRegId: "22VBRES5678G1HP",
    address: "Plot 7, Electronic City Phase 1",
    city: "Bengaluru",
    pincode: "560100",
    description: "Running free coaching centres for competitive exam preparation for students from economically weaker sections.",
    logoUrl: "",
    status: "rejected",
    socialLinks: {
      website: "https://vidyabharati.edu.in",
      linkedin: "https://linkedin.com/company/vidyabharati",
      twitter: "https://twitter.com/vidyabharati",
    },
    submittedAt: "1 week ago",
  },
  {
    id: "6",
    name: "Paws & Claws Animal Rescue",
    contactPerson: "Priya Menon",
    email: "priya@pawsclaws.org",
    phone: "+91 43210 98765",
    gstOrRegId: "PCAR-NGO-2020-1122",
    address: "Behind City Market, Whitefield",
    city: "Bengaluru",
    pincode: "560066",
    description: "Animal rescue and rehabilitation centre focusing on stray dogs and cats. Operates a 24/7 rescue helpline and monthly adoption drives.",
    logoUrl: "",
    status: "pending",
    socialLinks: {
      instagram: "https://instagram.com/pawsclawsblr",
      facebook: "https://facebook.com/pawsclawsblr",
    },
    submittedAt: "1 day ago",
  },
];
